job_build_and_test:
    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    stage: build
    script:
      - yum -y install gcc-c++
      - yum -y install make
      - cd src
      - make
      - bin/scanConsole -r configs/emuCfg.json -c configs/test.json -s digitalscan
      - cd ../
