job_build_and_test:
    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    stage: build
    script:
      - yum -y install centos-release-scl-rh devtoolset-7 make gnuplot cmake3
      - scl enable devtoolset-7 bash
      - source /opt/rh/devtoolset-7/enable
      - mkdir  cmake_build
      - cd cmake_build
      - cmake3 .. -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-gcc
      - make install -j4
      - export USER=test
      - echo $USER
      - /bin/pwd
      - mkdir /tmp/test
      - ls /tmp/
      - cd ../installed
      - x86_64/bin/scanConsole -r configs/controller/emuCfg.json -c configs/connectivity/example_fei4b_setup.json -s configs/scans/fei4/std_digitalscan.json -p
      - ls
      - ls ./data/
      - ls ./data/000001_std_digitalscan/
      - cat ./data/000001_std_digitalscan/*_OccupancyMap.dat
      - NUM100=`cat ./data/000001_std_digitalscan/*_OccupancyMap.dat | grep -o 100 | wc -l`
      - if [ "$NUM100" != "26880" ]; then exit 2; fi
      - x86_64/bin/scanConsole -k

job_build_cmake:
    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    stage: build
    script:
      - yum -y install centos-release-scl-rh devtoolset-7 make cmake3 gnuplot
      - scl enable devtoolset-7 bash
      - source /opt/rh/devtoolset-7/enable
      - mkdir -p cmake_build
      - cd cmake_build
      - cmake3 .. -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-gcc
      - make install -j4
      - cd ../installed
      - x86_64/bin/scanConsole -k

job_test_json:
    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    stage: build
    script:
      - yum -y install npm
      - npm install jsonlint -g
      - for file in $(find ../src/configs/ -iname "*.json"); do echo ${file}; jsonlint -q ${file} || break -1; done

job_build_with_felix:
    # Image of pre-built felix software
    image: gitlab-registry.cern.ch/atlas-tdaq-felix/felix-image:cc7
    variables:
     # This is what is in the docker image!
     FELIX_DIR: /opt/felix/felix-nightly
     # LCG style config identifier
     CONFIG: x86_64-centos7-gcc62-opt
     GCC_SCRIPT: /cvmfs/sft.cern.ch/lcg/releases/gcc/6.2.0/x86_64-centos7/setup.sh
    tags:
     - cvmfs
    script:
     # Which versions are present
     - ls ${FELIX_DIR}/..
     # Which configurations are present
     - ls ${FELIX_DIR}
     # Which include files exist
     - find ${FELIX_DIR}/${CONFIG}/include -type f
     # Temporary fix for unexpected change in container (Apr '19)
     - "[[ -d ${FELIX_DIR}/${CONFIG}/include/netio ]] || mkdir ${FELIX_DIR}/${CONFIG}/include/netio"
     - "[[ -f ${FELIX_DIR}/${CONFIG}/include/netio/netio.hpp ]] || mv ${FELIX_DIR}/${CONFIG}/include/{,netio/}netio.hpp"
     - yum -y install cmake3 gnuplot glibc-devel which
     # Run setup for YARR
     - source ${FELIX_DIR}/${CONFIG}/setup.sh
     - source ${GCC_SCRIPT}
     - gcc --version
     - mkdir -p cmake_build
     - cd cmake_build
     - cmake3 .. -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-gcc -DENABLE_NETIO:BOOL=ON -DNETIO_DIR:PATH=${FELIX_DIR}/${CONFIG}
     - make install -j4
     - cd ../installed
     - x86_64/bin/scanConsole -k


