site_name: YARR Docs
pages:
    - Home: index.md
    - SW Installation: install.md
    - Kernel Driver: kernel_driver.md
    - PCIe Firmware: pcie.md
    - External PCIe: pcie_ext.md
    - ScanConsole: scanconsole.md
    - FE-I4: fei4.md
    - FE65-P2: fe65p2.md
    - RD53A: rd53a.md
    - Star: star.md
    - Local DB: localdb.md
    - Plotting Tools: plotting.md
    - Logging configuration: logging.md
    - Firmware Guide: fw_guide.md
    - NetIO: netio.md
    - Troubleshooting: troubleshooting.md
    - Emulator: emulator.md
    - Version Log: version.md
theme: readthedocs
